// Mocks generated by Mockito 5.4.6 from annotations
// in into_the_wild/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:convert' as _i10;
import 'dart:typed_data' as _i12;
import 'dart:ui' as _i17;

import 'package:async/async.dart' as _i15;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i23;
import 'package:google_sign_in/google_sign_in.dart' as _i3;
import 'package:google_sign_in_platform_interface/google_sign_in_platform_interface.dart'
    as _i14;
import 'package:http/http.dart' as _i2;
import 'package:image_picker/image_picker.dart' as _i8;
import 'package:into_the_wild/models/chat_message.dart' as _i20;
import 'package:into_the_wild/models/conversation.dart' as _i7;
import 'package:into_the_wild/models/user.dart' as _i6;
import 'package:into_the_wild/services/auth_service.dart' as _i18;
import 'package:into_the_wild/services/chat_service.dart' as _i21;
import 'package:into_the_wild/services/conversation_service.dart' as _i19;
import 'package:into_the_wild/services/notification_service.dart' as _i22;
import 'package:into_the_wild/services/websocket_service.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:shared_preferences/shared_preferences.dart' as _i13;
import 'package:speech_to_text/speech_to_text.dart' as _i24;
import 'package:stream_channel/stream_channel.dart' as _i5;
import 'package:web_socket_channel/web_socket_channel.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_1 extends _i1.SmartFake
    implements _i2.StreamedResponse {
  _FakeStreamedResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoogleSignInAuthentication_2 extends _i1.SmartFake
    implements _i3.GoogleSignInAuthentication {
  _FakeGoogleSignInAuthentication_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebSocketSink_3 extends _i1.SmartFake implements _i4.WebSocketSink {
  _FakeWebSocketSink_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamChannel_4<T> extends _i1.SmartFake
    implements _i5.StreamChannel<T> {
  _FakeStreamChannel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_5 extends _i1.SmartFake implements _i6.User {
  _FakeUser_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversation_6 extends _i1.SmartFake implements _i7.Conversation {
  _FakeConversation_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLostDataResponse_7 extends _i1.SmartFake
    implements _i8.LostDataResponse {
  _FakeLostDataResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i2.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i9.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i9.Future<_i2.Response>);

  @override
  _i9.Future<_i2.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i9.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i9.Future<_i2.Response>);

  @override
  _i9.Future<_i2.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i9.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i9.Future<_i2.Response>);

  @override
  _i9.Future<_i2.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i9.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i9.Future<_i2.Response>);

  @override
  _i9.Future<_i2.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i9.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i9.Future<_i2.Response>);

  @override
  _i9.Future<_i2.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i9.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i9.Future<_i2.Response>);

  @override
  _i9.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i9.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<_i12.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i9.Future<_i12.Uint8List>.value(_i12.Uint8List(0)),
          )
          as _i9.Future<_i12.Uint8List>);

  @override
  _i9.Future<_i2.StreamedResponse> send(_i2.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i9.Future<_i2.StreamedResponse>.value(
              _FakeStreamedResponse_1(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i9.Future<_i2.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i13.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i9.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [GoogleSignIn].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignIn extends _i1.Mock implements _i3.GoogleSignIn {
  MockGoogleSignIn() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.SignInOption get signInOption =>
      (super.noSuchMethod(
            Invocation.getter(#signInOption),
            returnValue: _i14.SignInOption.standard,
          )
          as _i14.SignInOption);

  @override
  List<String> get scopes =>
      (super.noSuchMethod(Invocation.getter(#scopes), returnValue: <String>[])
          as List<String>);

  @override
  bool get forceCodeForRefreshToken =>
      (super.noSuchMethod(
            Invocation.getter(#forceCodeForRefreshToken),
            returnValue: false,
          )
          as bool);

  @override
  _i9.Stream<_i3.GoogleSignInAccount?> get onCurrentUserChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onCurrentUserChanged),
            returnValue: _i9.Stream<_i3.GoogleSignInAccount?>.empty(),
          )
          as _i9.Stream<_i3.GoogleSignInAccount?>);

  @override
  _i9.Future<_i3.GoogleSignInAccount?> signInSilently({
    bool? suppressErrors = true,
    bool? reAuthenticate = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInSilently, [], {
              #suppressErrors: suppressErrors,
              #reAuthenticate: reAuthenticate,
            }),
            returnValue: _i9.Future<_i3.GoogleSignInAccount?>.value(),
          )
          as _i9.Future<_i3.GoogleSignInAccount?>);

  @override
  _i9.Future<bool> isSignedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isSignedIn, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<_i3.GoogleSignInAccount?> signIn() =>
      (super.noSuchMethod(
            Invocation.method(#signIn, []),
            returnValue: _i9.Future<_i3.GoogleSignInAccount?>.value(),
          )
          as _i9.Future<_i3.GoogleSignInAccount?>);

  @override
  _i9.Future<_i3.GoogleSignInAccount?> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i9.Future<_i3.GoogleSignInAccount?>.value(),
          )
          as _i9.Future<_i3.GoogleSignInAccount?>);

  @override
  _i9.Future<_i3.GoogleSignInAccount?> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i9.Future<_i3.GoogleSignInAccount?>.value(),
          )
          as _i9.Future<_i3.GoogleSignInAccount?>);

  @override
  _i9.Future<bool> requestScopes(List<String>? scopes) =>
      (super.noSuchMethod(
            Invocation.method(#requestScopes, [scopes]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> canAccessScopes(
    List<String>? scopes, {
    String? accessToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #canAccessScopes,
              [scopes],
              {#accessToken: accessToken},
            ),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);
}

/// A class which mocks [GoogleSignInAccount].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockGoogleSignInAccount extends _i1.Mock
    implements _i3.GoogleSignInAccount {
  MockGoogleSignInAccount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i11.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  _i9.Future<_i3.GoogleSignInAuthentication> get authentication =>
      (super.noSuchMethod(
            Invocation.getter(#authentication),
            returnValue: _i9.Future<_i3.GoogleSignInAuthentication>.value(
              _FakeGoogleSignInAuthentication_2(
                this,
                Invocation.getter(#authentication),
              ),
            ),
          )
          as _i9.Future<_i3.GoogleSignInAuthentication>);

  @override
  _i9.Future<Map<String, String>> get authHeaders =>
      (super.noSuchMethod(
            Invocation.getter(#authHeaders),
            returnValue: _i9.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i9.Future<Map<String, String>>);

  @override
  _i9.Future<void> clearAuthCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAuthCache, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [GoogleSignInAuthentication].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignInAuthentication extends _i1.Mock
    implements _i3.GoogleSignInAuthentication {
  MockGoogleSignInAuthentication() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [WebSocketChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketChannel extends _i1.Mock implements _i4.WebSocketChannel {
  MockWebSocketChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<void> get ready =>
      (super.noSuchMethod(
            Invocation.getter(#ready),
            returnValue: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Stream<dynamic> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i9.Stream<dynamic>.empty(),
          )
          as _i9.Stream<dynamic>);

  @override
  _i4.WebSocketSink get sink =>
      (super.noSuchMethod(
            Invocation.getter(#sink),
            returnValue: _FakeWebSocketSink_3(this, Invocation.getter(#sink)),
          )
          as _i4.WebSocketSink);

  @override
  void pipe(_i5.StreamChannel<dynamic>? other) => super.noSuchMethod(
    Invocation.method(#pipe, [other]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.StreamChannel<S> transform<S>(
    _i5.StreamChannelTransformer<S, dynamic>? transformer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#transform, [transformer]),
            returnValue: _FakeStreamChannel_4<S>(
              this,
              Invocation.method(#transform, [transformer]),
            ),
          )
          as _i5.StreamChannel<S>);

  @override
  _i5.StreamChannel<dynamic> transformStream(
    _i9.StreamTransformer<dynamic, dynamic>? transformer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#transformStream, [transformer]),
            returnValue: _FakeStreamChannel_4<dynamic>(
              this,
              Invocation.method(#transformStream, [transformer]),
            ),
          )
          as _i5.StreamChannel<dynamic>);

  @override
  _i5.StreamChannel<dynamic> transformSink(
    _i15.StreamSinkTransformer<dynamic, dynamic>? transformer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#transformSink, [transformer]),
            returnValue: _FakeStreamChannel_4<dynamic>(
              this,
              Invocation.method(#transformSink, [transformer]),
            ),
          )
          as _i5.StreamChannel<dynamic>);

  @override
  _i5.StreamChannel<dynamic> changeStream(
    _i9.Stream<dynamic> Function(_i9.Stream<dynamic>)? change,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeStream, [change]),
            returnValue: _FakeStreamChannel_4<dynamic>(
              this,
              Invocation.method(#changeStream, [change]),
            ),
          )
          as _i5.StreamChannel<dynamic>);

  @override
  _i5.StreamChannel<dynamic> changeSink(
    _i9.StreamSink<dynamic> Function(_i9.StreamSink<dynamic>)? change,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeSink, [change]),
            returnValue: _FakeStreamChannel_4<dynamic>(
              this,
              Invocation.method(#changeSink, [change]),
            ),
          )
          as _i5.StreamChannel<dynamic>);

  @override
  _i5.StreamChannel<S> cast<S>() =>
      (super.noSuchMethod(
            Invocation.method(#cast, []),
            returnValue: _FakeStreamChannel_4<S>(
              this,
              Invocation.method(#cast, []),
            ),
          )
          as _i5.StreamChannel<S>);
}

/// A class which mocks [WebSocketSink].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketSink extends _i1.Mock implements _i4.WebSocketSink {
  MockWebSocketSink() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<dynamic> get done =>
      (super.noSuchMethod(
            Invocation.getter(#done),
            returnValue: _i9.Future<dynamic>.value(),
          )
          as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> close([int? closeCode, String? closeReason]) =>
      (super.noSuchMethod(
            Invocation.method(#close, [closeCode, closeReason]),
            returnValue: _i9.Future<dynamic>.value(),
          )
          as _i9.Future<dynamic>);

  @override
  void add(dynamic data) => super.noSuchMethod(
    Invocation.method(#add, [data]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<dynamic> addStream(_i9.Stream<dynamic>? stream) =>
      (super.noSuchMethod(
            Invocation.method(#addStream, [stream]),
            returnValue: _i9.Future<dynamic>.value(),
          )
          as _i9.Future<dynamic>);
}

/// A class which mocks [WebSocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketService extends _i1.Mock implements _i16.WebSocketService {
  MockWebSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i9.Future<void> connect(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [userId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void sendMessage({
    required String? text,
    required String? conversationId,
    required String? userName,
    required String? userId,
    String? clientMessageId,
  }) => super.noSuchMethod(
    Invocation.method(#sendMessage, [], {
      #text: text,
      #conversationId: conversationId,
      #userName: userName,
      #userId: userId,
      #clientMessageId: clientMessageId,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void sendImageMessage({
    String? imageUrl,
    String? imageBase64,
    String? imageMimeType,
    required String conversationId,
    required String userName,
    required String userId,
    String text = "",
    String? clientMessageId,
  }) => super.noSuchMethod(
    Invocation.method(#sendImageMessage, [], {
      #imageUrl: imageUrl,
      #imageBase64: imageBase64,
      #imageMimeType: imageMimeType,
      #conversationId: conversationId,
      #userName: userName,
      #userId: userId,
      #text: text,
      #clientMessageId: clientMessageId,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void joinConversation(String? conversationId) => super.noSuchMethod(
    Invocation.method(#joinConversation, [conversationId]),
    returnValueForMissingStub: null,
  );

  @override
  void requestAllGroups() => super.noSuchMethod(
    Invocation.method(#requestAllGroups, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i17.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i17.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i18.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i9.Future<_i6.User> register(String? username, {String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#register, [username], {#email: email}),
            returnValue: _i9.Future<_i6.User>.value(
              _FakeUser_5(
                this,
                Invocation.method(#register, [username], {#email: email}),
              ),
            ),
          )
          as _i9.Future<_i6.User>);

  @override
  _i9.Future<_i6.User?> getUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i9.Future<_i6.User?>.value(),
          )
          as _i9.Future<_i6.User?>);

  @override
  _i9.Future<_i6.User> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i9.Future<_i6.User>.value(
              _FakeUser_5(this, Invocation.method(#signInWithGoogle, [])),
            ),
          )
          as _i9.Future<_i6.User>);

  @override
  _i9.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void addListener(_i17.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i17.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ConversationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationService extends _i1.Mock
    implements _i19.ConversationService {
  MockConversationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i7.Conversation> get conversations =>
      (super.noSuchMethod(
            Invocation.getter(#conversations),
            returnValue: <_i7.Conversation>[],
          )
          as List<_i7.Conversation>);

  @override
  Map<String, String> get usernameCache =>
      (super.noSuchMethod(
            Invocation.getter(#usernameCache),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i9.Future<_i7.Conversation> createConversation({
    String? name,
    required String? type,
    required List<String>? participantIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createConversation, [], {
              #name: name,
              #type: type,
              #participantIds: participantIds,
            }),
            returnValue: _i9.Future<_i7.Conversation>.value(
              _FakeConversation_6(
                this,
                Invocation.method(#createConversation, [], {
                  #name: name,
                  #type: type,
                  #participantIds: participantIds,
                }),
              ),
            ),
          )
          as _i9.Future<_i7.Conversation>);

  @override
  _i9.Future<_i7.Conversation> getConversation(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversation, [conversationId]),
            returnValue: _i9.Future<_i7.Conversation>.value(
              _FakeConversation_6(
                this,
                Invocation.method(#getConversation, [conversationId]),
              ),
            ),
          )
          as _i9.Future<_i7.Conversation>);

  @override
  _i9.Future<List<_i20.ChatMessage>> getMessages(
    String? conversationId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [conversationId], {#limit: limit}),
            returnValue: _i9.Future<List<_i20.ChatMessage>>.value(
              <_i20.ChatMessage>[],
            ),
          )
          as _i9.Future<List<_i20.ChatMessage>>);

  @override
  _i9.Future<void> addBotToConversation(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#addBotToConversation, [conversationId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> removeBotFromConversation(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#removeBotFromConversation, [conversationId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void setCurrentConversation(_i7.Conversation? conversation) =>
      super.noSuchMethod(
        Invocation.method(#setCurrentConversation, [conversation]),
        returnValueForMissingStub: null,
      );

  @override
  void loadConversations(List<_i7.Conversation>? conversations) =>
      super.noSuchMethod(
        Invocation.method(#loadConversations, [conversations]),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<List<_i7.Conversation>> getAllConversations(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getAllConversations, [userId]),
            returnValue: _i9.Future<List<_i7.Conversation>>.value(
              <_i7.Conversation>[],
            ),
          )
          as _i9.Future<List<_i7.Conversation>>);

  @override
  _i9.Future<_i7.Conversation> joinGroup(
    String? conversationId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#joinGroup, [conversationId, userId]),
            returnValue: _i9.Future<_i7.Conversation>.value(
              _FakeConversation_6(
                this,
                Invocation.method(#joinGroup, [conversationId, userId]),
              ),
            ),
          )
          as _i9.Future<_i7.Conversation>);

  @override
  _i9.Future<_i7.Conversation> leaveGroup(
    String? conversationId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#leaveGroup, [conversationId, userId]),
            returnValue: _i9.Future<_i7.Conversation>.value(
              _FakeConversation_6(
                this,
                Invocation.method(#leaveGroup, [conversationId, userId]),
              ),
            ),
          )
          as _i9.Future<_i7.Conversation>);

  @override
  void addOrUpdateConversation(_i7.Conversation? conversation) =>
      super.noSuchMethod(
        Invocation.method(#addOrUpdateConversation, [conversation]),
        returnValueForMissingStub: null,
      );

  @override
  void updateUsernameCache(String? userId, String? username) =>
      super.noSuchMethod(
        Invocation.method(#updateUsernameCache, [userId, username]),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i17.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i17.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ChatService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatService extends _i1.Mock implements _i21.ChatService {
  MockChatService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i20.ChatMessage> get messages =>
      (super.noSuchMethod(
            Invocation.getter(#messages),
            returnValue: <_i20.ChatMessage>[],
          )
          as List<_i20.ChatMessage>);

  @override
  bool get isListening =>
      (super.noSuchMethod(Invocation.getter(#isListening), returnValue: false)
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void initializeServices({
    required _i16.WebSocketService? webSocketService,
    required _i19.ConversationService? conversationService,
    required _i18.AuthService? authService,
  }) => super.noSuchMethod(
    Invocation.method(#initializeServices, [], {
      #webSocketService: webSocketService,
      #conversationService: conversationService,
      #authService: authService,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> loadConversation(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#loadConversation, [conversationId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> sendTextMessage(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#sendTextMessage, [text]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> sendImageMessage(String? imagePath) =>
      (super.noSuchMethod(
            Invocation.method(#sendImageMessage, [imagePath]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> startListening() =>
      (super.noSuchMethod(
            Invocation.method(#startListening, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> stopListening() =>
      (super.noSuchMethod(
            Invocation.method(#stopListening, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String?> pickImageFromCamera() =>
      (super.noSuchMethod(
            Invocation.method(#pickImageFromCamera, []),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<String?> pickImageFromGallery() =>
      (super.noSuchMethod(
            Invocation.method(#pickImageFromGallery, []),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<void> sendImageMessageFromXFile(_i8.XFile? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#sendImageMessageFromXFile, [imageFile]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void clearMessages() => super.noSuchMethod(
    Invocation.method(#clearMessages, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearConversation() => super.noSuchMethod(
    Invocation.method(#clearConversation, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i17.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i17.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i22.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Stream<_i23.NotificationResponse> get notificationResponseStream =>
      (super.noSuchMethod(
            Invocation.getter(#notificationResponseStream),
            returnValue: _i9.Stream<_i23.NotificationResponse>.empty(),
          )
          as _i9.Stream<_i23.NotificationResponse>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i9.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void setCurrentConversationId(String? conversationId) => super.noSuchMethod(
    Invocation.method(#setCurrentConversationId, [conversationId]),
    returnValueForMissingStub: null,
  );

  @override
  int getTotalUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalUnreadCount, []),
            returnValue: 0,
          )
          as int);

  @override
  int getUnreadCount(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCount, [conversationId]),
            returnValue: 0,
          )
          as int);

  @override
  _i9.Future<bool> showMessageNotification({
    required String? conversationId,
    required String? messageText,
    required String? senderName,
    String? conversationName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showMessageNotification, [], {
              #conversationId: conversationId,
              #messageText: messageText,
              #senderName: senderName,
              #conversationName: conversationName,
            }),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> cancelAll() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAll, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> cancelConversationNotifications(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelConversationNotifications, [
              conversationId,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void clearAllUnreadCounts() => super.noSuchMethod(
    Invocation.method(#clearAllUnreadCounts, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i17.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i17.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SpeechToText].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpeechToText extends _i1.Mock implements _i24.SpeechToText {
  MockSpeechToText() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasRecognized =>
      (super.noSuchMethod(Invocation.getter(#hasRecognized), returnValue: false)
          as bool);

  @override
  String get lastRecognizedWords =>
      (super.noSuchMethod(
            Invocation.getter(#lastRecognizedWords),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#lastRecognizedWords),
            ),
          )
          as String);

  @override
  String get lastStatus =>
      (super.noSuchMethod(
            Invocation.getter(#lastStatus),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#lastStatus),
            ),
          )
          as String);

  @override
  double get lastSoundLevel =>
      (super.noSuchMethod(Invocation.getter(#lastSoundLevel), returnValue: 0.0)
          as double);

  @override
  bool get isAvailable =>
      (super.noSuchMethod(Invocation.getter(#isAvailable), returnValue: false)
          as bool);

  @override
  bool get isListening =>
      (super.noSuchMethod(Invocation.getter(#isListening), returnValue: false)
          as bool);

  @override
  bool get isNotListening =>
      (super.noSuchMethod(
            Invocation.getter(#isNotListening),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasError =>
      (super.noSuchMethod(Invocation.getter(#hasError), returnValue: false)
          as bool);

  @override
  _i9.Future<bool> get hasPermission =>
      (super.noSuchMethod(
            Invocation.getter(#hasPermission),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  set errorListener(_i24.SpeechErrorListener? value) => super.noSuchMethod(
    Invocation.setter(#errorListener, value),
    returnValueForMissingStub: null,
  );

  @override
  set statusListener(_i24.SpeechStatusListener? value) => super.noSuchMethod(
    Invocation.setter(#statusListener, value),
    returnValueForMissingStub: null,
  );

  @override
  set unexpectedPhraseAggregator(_i24.SpeechPhraseAggregator? value) =>
      super.noSuchMethod(
        Invocation.setter(#unexpectedPhraseAggregator, value),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<bool> initialize({
    _i24.SpeechErrorListener? onError,
    _i24.SpeechStatusListener? onStatus,
    dynamic debugLogging = false,
    Duration? finalTimeout = const Duration(milliseconds: 2000),
    List<_i24.SpeechConfigOption>? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #onError: onError,
              #onStatus: onStatus,
              #debugLogging: debugLogging,
              #finalTimeout: finalTimeout,
              #options: options,
            }),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> cancel() =>
      (super.noSuchMethod(
            Invocation.method(#cancel, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<dynamic> listen({
    _i24.SpeechResultListener? onResult,
    Duration? listenFor,
    Duration? pauseFor,
    String? localeId,
    _i24.SpeechSoundLevelChange? onSoundLevelChange,
    dynamic cancelOnError = false,
    dynamic partialResults = true,
    dynamic onDevice = false,
    _i24.ListenMode? listenMode = _i24.ListenMode.confirmation,
    dynamic sampleRate = 0,
    _i24.SpeechListenOptions? listenOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listen, [], {
              #onResult: onResult,
              #listenFor: listenFor,
              #pauseFor: pauseFor,
              #localeId: localeId,
              #onSoundLevelChange: onSoundLevelChange,
              #cancelOnError: cancelOnError,
              #partialResults: partialResults,
              #onDevice: onDevice,
              #listenMode: listenMode,
              #sampleRate: sampleRate,
              #listenOptions: listenOptions,
            }),
            returnValue: _i9.Future<dynamic>.value(),
          )
          as _i9.Future<dynamic>);

  @override
  void changePauseFor(Duration? pauseFor) => super.noSuchMethod(
    Invocation.method(#changePauseFor, [pauseFor]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<List<_i24.LocaleName>> locales() =>
      (super.noSuchMethod(
            Invocation.method(#locales, []),
            returnValue: _i9.Future<List<_i24.LocaleName>>.value(
              <_i24.LocaleName>[],
            ),
          )
          as _i9.Future<List<_i24.LocaleName>>);

  @override
  _i9.Future<_i24.LocaleName?> systemLocale() =>
      (super.noSuchMethod(
            Invocation.method(#systemLocale, []),
            returnValue: _i9.Future<_i24.LocaleName?>.value(),
          )
          as _i9.Future<_i24.LocaleName?>);
}

/// A class which mocks [ImagePicker].
///
/// See the documentation for Mockito's code generation for more information.
class MockImagePicker extends _i1.Mock implements _i8.ImagePicker {
  MockImagePicker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i8.XFile?> pickImage({
    required _i8.ImageSource? source,
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    _i8.CameraDevice? preferredCameraDevice = _i8.CameraDevice.rear,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickImage, [], {
              #source: source,
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #preferredCameraDevice: preferredCameraDevice,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i9.Future<_i8.XFile?>.value(),
          )
          as _i9.Future<_i8.XFile?>);

  @override
  _i9.Future<List<_i8.XFile>> pickMultiImage({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMultiImage, [], {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #limit: limit,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i9.Future<List<_i8.XFile>>.value(<_i8.XFile>[]),
          )
          as _i9.Future<List<_i8.XFile>>);

  @override
  _i9.Future<_i8.XFile?> pickMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMedia, [], {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i9.Future<_i8.XFile?>.value(),
          )
          as _i9.Future<_i8.XFile?>);

  @override
  _i9.Future<List<_i8.XFile>> pickMultipleMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMultipleMedia, [], {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #limit: limit,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i9.Future<List<_i8.XFile>>.value(<_i8.XFile>[]),
          )
          as _i9.Future<List<_i8.XFile>>);

  @override
  _i9.Future<_i8.XFile?> pickVideo({
    required _i8.ImageSource? source,
    _i8.CameraDevice? preferredCameraDevice = _i8.CameraDevice.rear,
    Duration? maxDuration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickVideo, [], {
              #source: source,
              #preferredCameraDevice: preferredCameraDevice,
              #maxDuration: maxDuration,
            }),
            returnValue: _i9.Future<_i8.XFile?>.value(),
          )
          as _i9.Future<_i8.XFile?>);

  @override
  _i9.Future<List<_i8.XFile>> pickMultiVideo({
    Duration? maxDuration,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMultiVideo, [], {
              #maxDuration: maxDuration,
              #limit: limit,
            }),
            returnValue: _i9.Future<List<_i8.XFile>>.value(<_i8.XFile>[]),
          )
          as _i9.Future<List<_i8.XFile>>);

  @override
  _i9.Future<_i8.LostDataResponse> retrieveLostData() =>
      (super.noSuchMethod(
            Invocation.method(#retrieveLostData, []),
            returnValue: _i9.Future<_i8.LostDataResponse>.value(
              _FakeLostDataResponse_7(
                this,
                Invocation.method(#retrieveLostData, []),
              ),
            ),
          )
          as _i9.Future<_i8.LostDataResponse>);

  @override
  bool supportsImageSource(_i8.ImageSource? source) =>
      (super.noSuchMethod(
            Invocation.method(#supportsImageSource, [source]),
            returnValue: false,
          )
          as bool);
}
